Basic Details View Controller functionality, contacts not added yet
11foot8/RepresentsMe pull request #49
Opened 2019-03-07 18:06 UTC by varunadiga

<img width="459" alt="screen shot 2019-03-07 at 12 06 11 pm" src="https://user-images.githubusercontent.com/13663809/53978691-76623180-40d1-11e9-82b0-63353aa4dacc.png">

2019-03-07 18:08 UTC, tirtow reviewed
Not approved. Removes core feature.

2019-03-07 18:11 UTC, bzsinger commented on RepresentsMe/View Controllers/DetailsViewController.swift
> +    var passedName = String()
```
var official:Official {
	didSet {
	   officialName.text = ...
	}
}
```

2019-03-07 18:11 UTC, bzsinger requested changes
🦇

2019-03-11 23:03 UTC, bzsinger approved these changes
LGTM! 🔥

2019-03-15 03:08 UTC, merged